"""initial migration on mysql - all previous data lost

Revision ID: 06a5d7db67d2
Revises: 
Create Date: 2020-08-13 22:00:21.100092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a5d7db67d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=64), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_course_name'), 'courses', ['course_name'], unique=True)
    op.create_index(op.f('ix_courses_semester'), 'courses', ['semester'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('fullname', sa.String(length=64), nullable=True),
    sa.Column('department', sa.String(length=64), nullable=True),
    sa.Column('faculty', sa.String(length=64), nullable=True),
    sa.Column('university', sa.String(length=64), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.create_index(op.f('ix_students_fullname'), 'students', ['fullname'], unique=False)
    op.create_index(op.f('ix_students_username'), 'students', ['username'], unique=True)
    op.create_table('journals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('journal_title', sa.String(length=64), nullable=True),
    sa.Column('journal', sa.Text(), nullable=True),
    sa.Column('journal_html', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journals_journal_title'), 'journals', ['journal_title'], unique=False)
    op.create_index(op.f('ix_journals_timestamp'), 'journals', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journals_timestamp'), table_name='journals')
    op.drop_index(op.f('ix_journals_journal_title'), table_name='journals')
    op.drop_table('journals')
    op.drop_index(op.f('ix_students_username'), table_name='students')
    op.drop_index(op.f('ix_students_fullname'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_courses_semester'), table_name='courses')
    op.drop_index(op.f('ix_courses_course_name'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
